name: simulation-mock-project
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: simulation_data      
      POSTGRES_USER: yassin          
      POSTGRES_PASSWORD: yassin      
    ports:
      - "5432:5432"                          
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
      - ./initdb:/docker-entrypoint-initdb.d  
    privileged: true
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"  
      PGADMIN_DEFAULT_PASSWORD: "admin"           
    ports:
      - "9090:80"                                 
    depends_on:
      - postgres

 ## if you have build the data-parser app you can run it using docker
 ## to build 
 # mvn clean package 
 # docker build -t data-parser .

  # spring-app:
  #   image: data-parser
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/simulation_data
  #     - SPRING_DATASOURCE_USERNAME=yassin
  #     - SPRING_DATASOURCE_PASSWORD=yassin
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #     - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
  #   # ports:
  #   #   - "9007:9007"   
  #   depends_on:
  #     - postgres
  #   network_mode: host
